import { UserRole } from "./user-roles";


export interface IProfile {
  id: string; // uuid, generated by gen_random_uuid()
  user_id: string; // foreign key to auth.users.id
  full_name?: string | null; // optional text

  created_at?: string; // timestamptz, default now()
  updated_at?: string; // timestamptz, auto updated by trigger

  is_active?: boolean; // default true
  is_deleted?: boolean; // default false
  is_banned?: boolean; // default false

  avatar_url?: string | null; // optional text

  role: UserRole; // enum: 'student' | 'teacher' | 'admin'
}
